### ISSUE TITLE
Limitations on SQL Statement

### ISSUE THREAD

**Issue by fabio2111** [openfigis/figis-sdi-qgis-plugins#1]
When executing  an Update SQL for areas with complex geometry (thus with many coordinates pairs) the following error is returned:

```
SQL Error: ORA-01704: string literal too long
01704. 00000 -  "string literal too long"
*Cause:    The string literal is longer than 4000 characters.
*Action:   Use a string literal of at most 4000 characters.
           Longer values may only be entered using bind variables.
```

**Comment by eblondel** [comment]
Thanks Fabio for reporting i'm going to have a look

**Comment by eblondel** [comment]
The limitation in the nb of characters is 4000 in SQL. It is a more in PL/SQL (~ 32K) but still not enough because geometry WKT strings can be much larger. 

To manage this, I've added a mechanism to switch to  a PL/SQL procedure combined with a chunks approach. This approach consists in spliting the WKT string into chunks of a size of 4000 characters at Python level, and write the PL/SQL procedure to fill a CLOB variable, that we can then pass, once filled with all chunks, to the SQL INSERT or UPDATE statement. 

It has been tested on large OARA polygons and it works well.

**Comment by fabio2111** [comment]
Thank you, it works very well. I am going to close the ticket

**Comment by saravatpt** [comment]
Simple solution that worked for me.

create table TEMPdemo ( x long );
declare
    myvar long default 'Your long string more than 4000 chars';
begin
   insert into TEMPdemo values ( myvar );
end;
